# Generated by Django 6.0.3 on 2026-03-18 21:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Место, где выполняется привычка', max_length=255, verbose_name='Место')),
                ('time', models.TimeField(help_text='Время выполнения привычки', verbose_name='Время')),
                ('action', models.TextField(help_text='Действие, которое представляет собой привычка', verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Приятная привычка')),
                ('periodicity', models.PositiveSmallIntegerField(default=1, help_text='Периодичность выполнения привычки для напоминания в днях', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Периодичность (в днях)')),
                ('reward', models.CharField(blank=True, help_text='Чем пользователь должен себя вознаградить после выполнения', max_length=255, null=True, verbose_name='Вознаграждение')),
                ('duration_sec', models.PositiveSmallIntegerField(help_text='Время, которое предположительно потратит пользователь', validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Время на выполнение (в секундах)')),
                ('is_public', models.BooleanField(default=False, help_text='Привычки можно публиковать в общий доступ', verbose_name='Публичная привычка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('linked_habit', models.ForeignKey(blank=True, help_text='Привычка, которая связана с другой привычкой', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['-created_at'],
            },
        ),
    ]
